### ISSUE TITLE
clipboard -  extra tab for Delivery and  Warehouse Resource tracking

### ISSUE THREAD

**Issue by Aduis1210** [ldtteam/minecolonies-features#164]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.

- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.291-ALPHA-universal
- Related Mods and their Versions: 

## Is your feature request related to a problem?
No Problem - just a feature request that I would feel beneficial.

## Enhancement or Change description
Just a quick suggestion for the Clipboard.
The ability to monitor deliveries that are in queue for couriers.
also the ability to change priority on a delivery by the clipboard.

Different tab to ensure its not clogging.
A clipboard can have multiple papers :) so it makes sense to add additional pages.

Also a resource tracker for the warehouse? As an additional suggestion?
The couriers can track so couldn't we add this to the clipboard as well?

### Notes or related things
Post Edit from original to include template - Notes added are from post discussion.

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

Hi there,

Just a quick suggestion for the Clipboard.
The ability to monitor deliveries that are in queue for couriers.
also the ability to change priority on a delivery by the clipboard.

just a thought 👍 
thanks

**Comment by ravenbuilder934** [comment]
Probably in a different tab so these wouldn't clog up the main tab. Could make it a button like the recent one to only show important requests ("Show being-fulfilled requests")?

**Comment by Aduis1210** [comment]
Different tab to ensure its not clogging.
A clipboard can have multiple papers :) so it makes sense to add addtional pages.

Also a resource tracker for the warehouse? As an additional suggestion?
The couriers can track so couldnt we add this to the clipboard as well?

**Comment by ravenbuilder934** [comment]
Warehouse resource tracker was refused unless it was static until you 'updated' it (shift+right-clicked on warehouse block) if I remember correctly.

**Comment by ravenbuilder934** [comment]
Warehouse tracker is already suggested, see https://github.com/ldtteam/minecolonies-features/issues/32. Otherwise sounds like an awesome tool to make sure your colony is functioning normally!

**Comment by haniawni** [comment]
I love both these ideas, but want to note that the bulk of my use case for a deliveries tracking tab is in checking for bugged/stuck/overwhelmed couriers rather than what the deliveries actually are. 

Same goals re: deliveries could be achieved just via a town-toggleable chat message if a delivery takes a long time, or if the number of deliveries scheduled on any single courier crosses X threshold, which may be less workload to implement?

**Comment by Thodor12** [comment]
This is implemented into the resource scroll, but no active tracking, we only display a static warehouse count for the duration of a build request, after that it will reset
